rootProject.name = "meeting-room-reserving-system"

include(":backend:user-service-interface")
include(":backend:user-service")
include(":backend:resource-service-interface")
include(":backend:resource-service")
include(":backend:booking-service-interface")
include(":backend:booking-service")
include(":backend:notification-service")
include(":backend:scheduler-service")
include(":backend:meeting-room-service-interface")
include(":backend:meeting-room-service")
include(":frontend:website-interface")
include(":frontend:website")
include(":frontend:backoffice-interface")
include(":frontend:backoffice")
include(":backend:user-service-db-migration")
include(":backend:booking-service-db-migration")
include(":backend:resource-service-db-migration")
